err_fun: mse # MSE
input_features: 17 
initializer: uniform # uniform OR xavier OR he
eta: 0.1 # 0 < eta < 1
alpha: 0.6 # parameter for momentum: 0.5 <= alpha <= 0.9. Out of this range, momentum is disabled
lambd: 0.01 # must be lambd > 0 for activating regularization
epochs: 1000 # epochs > 0
optimizer: gd # gd (Gradient Descent)
layers_config:
  units: [4, 1] # list len must be >0; values must be > 0
  activations: [relu, sigmoid] # identity OR relu OR sigmoid; list len must be equal to len of units