err_fun: mse # mse
metric: acc_bin # mee OR mse OR acc_bin
input_features: 784
initializer: xavier # uniform OR xavier OR he
eta: 0.1 # 0 < eta < 1
alpha: 0.7 # parameter for momentum: 0.5 <= alpha <= 0.9. Out of this range, momentum is disabled
lambd: 0.01 # must be lambd > 0 for activating regularization
epochs: 500 # epochs > 0
units: [64, 64, 10] # list len must be > 0; values must be > 0
activations: [relu, relu, sigmoid] # identity OR relu OR sigmoid; list len must be equal to len of units