task: bin_classification # bin_classification OR regression
input_features: 17
initializer: uniform # uniform OR xavier OR he
eta: 0.1 # 0 < eta < 1
momentum: True # True OR False
alpha: 0.6 # parameter for momentum: [0.5, 0.9]
epochs: 1000 # epochs > 0
optimizer: gd # gd (Gradient Descent)