task: bin_classification # bin_classification OR regression
input_features: 17
initializer: uniform # uniform OR xavier OR he
eta: 0.1 # 0 < eta < 1
momentum: False # True OR False
epochs: 2500 # epochs > 0
optimizer: gd # gd (Gradient Descent)